### ISSUE TITLE
Final comments to repo

### ISSUE THREAD

**Issue by AliciaMstt** [necrosnake91/Lung_cancer_transcriptome#13]
Your README is very well explained and clearly corresponds to your pipeline, which is also very clear. Well done and congratulations. I also liked the way your scripts are commented and organized. Your results summary is clear and makes good use of the figures, which are also very neat. Congratulations.

I only have the following concern regarding your scripts / figures, which I recommend you to attend:

I couldn't find the code to generate the volcano plots within your 6.Differential_expression_analysis.R. It seems this is something you used outside this script. Although this is documented in your Results.md, it is not good practice to separate the Figure from the script in this way. I recommend performing one of the following:

a) Moving the code to perform the volcano figures to the 6.Differential_expression_analysis.R script.
or
b) Making your Results.md file a .Rmd file, source the 6.Differential_expression_analysis.R script and running the extra code to perform the other figures in the .Rmd so that in a sense it is part of a script.

I hope you enjoyed the class.

**Comment by camillethuyentruong** [comment]
Hi Rodolfo,
I enjoyed going through your repository that is very clear and well-structured. Well done!

One additional comment:
In the README file, "result" is presented as a sub-directory inside of bin, instead of a directory.

Don't hesitate to get back to us if you need more feedback and good luck with your thesis!

**Comment by necrosnake91** [comment]
> Your README is very well explained and clearly corresponds to your pipeline, which is also very clear. Well done and congratulations. I also liked the way your scripts are commented and organized. Your results summary is clear and makes good use of the figures, which are also very neat. Congratulations.
> 
> I only have the following concern regarding your scripts / figures, which I recommend you to attend:
> 
> I couldn't find the code to generate the volcano plots within your 6.Differential_expression_analysis.R. It seems this is something you used outside this script. Although this is documented in your Results.md, it is not good practice to separate the Figure from the script in this way. I recommend performing one of the following:
> 
> a) Moving the code to perform the volcano figures to the 6.Differential_expression_analysis.R script.
> or
> b) Making your Results.md file a .Rmd file, source the 6.Differential_expression_analysis.R script and running the extra code to perform the other figures in the .Rmd so that in a sense it is part of a script.
> 
> I hope you enjoyed the class.

Hi Alicia, thanks again for the feedback and your comments. You are right, the code to generate each volcano plots it is not included in the script 6.Differential_expression_analysis.R, I forgot to update it adding these lines. However, I'm going to put this in the final version of the code or try to generate the .Rmd file.
About the class, thanks again for all your time, comments, knowledge, and feedback. I'm motivated to learn more in the bioinformatics field and to participate in new projects. I enjoyed so much the class.

**Comment by necrosnake91** [comment]
> Hi Rodolfo,
> I enjoyed going through your repository that is very clear and well-structured. Well done!
> 
> One additional comment:
> In the README file, "result" is presented as a sub-directory inside of bin, instead of a directory. It could deserve a little more explanation on the new analyses that you have added.
> 
> Don't hesitate to get back to us if you need more feedback and good luck with your thesis!

Hi Camille,

Thanks again for your comments. Now, watching the README file, it looks like the Results/ directory is part of bin/. I'm going to edit the file to set clearer this part and to add new a deeper explanation of this directory.

Thanks again for all the support and feedback during and outside the class. As I told Alicia, I'm motivated to keep going in the bioinformatics field after learning a lot of things in class.

**Comment by AliciaMstt** [comment]
:)
