### ISSUE TITLE
Calculating the Q30 using a loop

### ISSUE THREAD

**Issue by necrosnake91** [necrosnake91/Lung_cancer_transcriptome#7]
Percentage of Q30 reads is a helpful tool to estimate the general quality of sequencing data.
BBtools has the shell script "bbduk" to perform this quality estimation.
The command to run "bbduk" and calculate Q30 is:

`.../pathtobbduk/bbduk.sh in1=input.R1.fq in2=input.R2.fq trimq=30 qtrim=rl`
In my last analysis, I´ve realized that I was "DRY"ing myself copying and pasting the name of each sample in "in1=" and "in2="
The names of my files are the next: t01, t02, t03 and t04
So:

- [x] How can I build a for loop to perform the calculation of each paired sample?

- [x] How can I save the result of the analysis of every paired sample in a file?

**Comment by tono2204** [comment]
``` 
for i in {1..100}
   do 
      ../bbmap/bbduk.sh in1=../t0${i}-R1.fastq in2=../t0${i}-R2.fastq trimq=30 qtrim=30 out=t0${i}.fq
      if [ $i -gt 9 ]
      then 
      ../bbmap/bbduk.sh in1=../t${i}-R1.fastq in2=../t${i}-R2.fastq trimq=30 qtrim=30 out=t${i}.fq
      fi
          
   done
 ```

Este script va de 1 a 100 y te haría el análisis para las primeras 100 muestras. También toma en cuenta que del 1 al 9 es 01,02,03, ..., 09

**Comment by necrosnake91** [comment]
> ```
> for i in {1..100}
>    do 
>       ../bbmap/bbduk.sh in1=../t0${i}-R1.fastq in2=../t0${i}-R2.fastq trimq=30 qtrim=30 out=t0${i}.fq
>       if [ $i -gt 9 ]
>       then 
>       ../bbmap/bbduk.sh in1=../t${i}-R1.fastq in2=../t${i}-R2.fastq trimq=30 qtrim=30 out=t${i}.fq
>       fi
>           
>    done
> ```
> 
> Este script va de 1 a 100 y te haría el análisis para las primeras 100 muestras. También toma en cuenta que del 1 al 9 es 01,02,03, ..., 09

We ran this script and realized that we must put the name of each sample (forward and reverse) in a list using a for loop. Afterward, ran the bbduk.sh script with the corresponding arguments. A few hours ago, we built this script:

```
for i in {1..2}; do
samplesr1="t0$i-R1.fastq " #Create the list for the forward files
samplesr2="t0$i-R2.fastq " #Create the list for the reverse files
../bbmap/bbduk.sh in1=../$samplesr1 in2=../$samplesr2 trimq=30 qtrim=rl
done

```

And obtained the expected result. Now, we are trying to figure out how to print the results from the analysis and save it in a file.

Thx Toño

**Comment by necrosnake91** [comment]
I have good news!!

Finally, I asked for help in SEQanswers and the issue regarding to save the output statistics from the analysis has been already solved!

I leave you the code:
````
for i in {1..2}; do
samplesr1="t0$i-R1.fastq " #Create the list for the forward files
samplesr2="t0$i-R2.fastq " #Create the list for the reverse files
../bbmap/bbduk.sh in1=../$samplesr1 in2=../$samplesr2 trimq=30 qtrim=rl
done &> example.txt
```
The command ```&>``` redirects the StdErr and StdOut to a file and works using this script.

Once again, Thx!
