### ISSUE TITLE
Concatenating fastq files

### ISSUE THREAD

**Issue by necrosnake91** [necrosnake91/Lung_cancer_transcriptome#9]
After the sequencing of the samples, I obtained the fastq files splitted in 4 files and stored in folders in the next way:

```
+--data/
|
|    +--536_L001-ds.afb18a9314a74bb4a8509a1eb291e3cb/
|          +--t013_1_R1.fastq
|          +--t013_1_R2.fastq
|    +--536_L002-ds.54b91bc2dee543bbba811eab9c0342f8/
|          +--t013_2_R1.fastq
|          +--t013_2_R2.fastq
|    +--536_L003-ds.619d39cdc63148768ecb631228a2ad41/
|          +--t013_3_R1.fastq
|          +--t013_3_R2.fastq
|    +--536_L004-ds.619d39cdc63148768ecb631228a2ad41/
|          +--t013_4_R1.fastq
|          +--t013_4_R2.fastq
```
With the next script I extracted the files from their respective folder and moved them into the folder **```data/```**
```
directory=`ls`
 
#Move all the files inside each directory towards data
for i in $directory; do
cd $i
mv * ../
cd ..
done
```
After moving all fastq files for every sample into the **```data/```** folder, I have the next arrange:

```
|          +--t013_1_R1.fastq
|          +--t013_1_R2.fastq
|          +--t013_2_R1.fastq
|          +--t013_2_R2.fastq
|          +--t013_3_R1.fastq
|          +--t013_3_R2.fastq
|          +--t013_4_R1.fastq
|          +--t013_4_R2.fastq
|
|          +--t014_1_R1.fastq
|          +--t014_1_R2.fastq
|          +--t014_2_R1.fastq
|          +--t014_2_R2.fastq
|          +--t014_3_R1.fastq
|          +--t014_3_R2.fastq
|          +--t014_4_R1.fastq
|          +--t014_4_R2.fastq
```
## **My issue**

I'm trying to concatenate the four files for the forward (R1) and the reverse (R2) reads of each sample. In my previous samples, I made this by hand and I realized that it is likely to commit mistakes in this process. To concatenate the files, I ran ```cat t01_1_R1.fastq t01_2_R1.fastq t01_3_R1.fastq t01_4_R1.fastq > t01-R1.fastq``` **for every R1 and R2 file of each sample!**.
I have an idea to fix this problem. Perhaps, using regular expressions or constructing arrays with the name of the samples could work.

**Comment by Rodolfo47** [comment]
can you give us access to the files? ore some toy files..

**Comment by necrosnake91** [comment]
Yup! This is the link to the files:

https://github.com/necrosnake91/fakerepository

**Comment by FernandaDiaz12** [comment]
#### Hi, you can try this: 

for R in $(ls | grep "t0" | uniq)
do
cat $(ls | grep *"t0"| uniq).R1.fastq > $(ls | grep "t0"| uniq).R1.fastq
done 

Where: 

- **ls.-**  lists the files and pipes it to grep
- **grep * "t0".-** search all files that start with the name "t0" something. 
- **uniq.-** Only one name at a time. 


#### :)

**Comment by FernandaDiaz12** [comment]
To check if the regular expressions to define the list are correct, you can "echo" the loop first.

**Comment by necrosnake91** [comment]
Fer,

I ran your script, and changing ```echo``` instead ```cat``` I obtained the next output:

```
t013_1_R1.txt.R1.txt > t013_1_R1.txt
t013_1_R2.txt.R1.txt > t013_1_R2.txt
t013_2_R1.txt.R1.txt > t013_2_R1.txt
t013_2_R2.txt.R1.txt > t013_2_R2.txt
t013_3_R1.txt.R1.txt > t013_3_R1.txt
t013_3_R2.txt.R1.txt > t013_3_R2.txt
t013_4_R1.txt.R1.txt > t013_4_R1.txt
t013_4_R2.txt.R1.txt > t013_4_R2.txt
t014_1_R1.txt.R1.txt > t014_1_R1.txt
t014_1_R2.txt.R1.txt > t014_1_R2.txt
t014_2_R1.txt.R1.txt > t014_2_R1.txt
t014_2_R2.txt.R1.txt > t014_2_R2.txt
t014_3_R1.txt.R1.txt > t014_3_R1.txt
t014_3_R2.txt.R1.txt > t014_3_R2.txt
t014_4_R1.txt.R1.txt > t014_4_R1.txt
t014_4_R2.txt.R1.txt > t014_4_R2.txt
t015_1_R1.txt.R1.txt > t015_1_R1.txt
t015_1_R2.txt.R1.txt > t015_1_R2.txt
t015_2_R1.txt.R1.txt > t015_2_R1.txt
t015_2_R2.txt.R1.txt > t015_2_R2.txt
t015_3_R1.txt.R1.txt > t015_3_R1.txt
t015_3_R2.txt.R1.txt > t015_3_R2.txt
t015_4_R1.txt.R1.txt > t015_4_R1.txt
t015_4_R2.txt.R1.txt > t015_4_R2.txt
```
It looks like this script is only creating new files with the same name of the older.

**Comment by Duhyadi** [comment]
I think the following script is a good guide`for i in {13..15}; do echo cat t0"$i"* > combined_"$i".txt; done`

**Comment by Rodolfo47** [comment]
you can use this annidated loops, after create directories and move the files:
```
#bin/sh

#add here mkdir and mv comands
#cd to R1 dir
for i in {13..15};
do
for j in {1..4};
do
cat t0${i}_${j}_R1.txt >> t0${i}-R1.fq
done
done

#cd to R2 dir
for i in {13..15};
do
for j in {1..4};
do
cat t0${i}_${j}_R2.txt >> t0${i}-R2.fq
done
done
```

**Comment by necrosnake91** [comment]
Rodo!

The script worked! 

Thanks
